### PR TITLE
Remove DS blocks table.

### PR DESCRIPTION
**Pull request by yaron-zilliqa**

### CODE REVIEW

**Review by rrw-zilliqa — CHANGES_REQUESTED** [review]
Rather than removing the code, can we hide this behind a developer flag please? Let's discuss in slack (and I can write an RFC if nec)

**Comment by yaron-zilliqa** [comment]
> Rather than removing the code, can we hide this behind a developer flag please? Let's discuss in slack (and I can write an RFC if nec)

Made this block conditional on a URL param called 'dev'. When set to 1 the recent DS blocks will be presented. Otherwise it will be hidden. The default is non-dev.

**Review by mauromedda — DISMISSED** [review]

**Review by mauromedda — APPROVED** [review]

**Comment by yaron-zilliqa** [comment]
> Rather than removing the code, can we hide this behind a developer flag please? Let's discuss in slack (and I can write an RFC if nec)

Done. Will depend on the value of a query param isDev.

**Review by mauromedda — APPROVED** [review]

**Review by rrw-zilliqa — APPROVED** [review]
Sorry for the delay - looks good to me :-)

**Pull request merged**
